# Cesvi Indice Infanzia - Esplorazione dati

In [1]:
import pandas as pd
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

In [38]:
df = pd.read_csv("cesvi-indiceinfanzia_data.csv")
df_meta = pd.read_csv("cesvi-indiceinfanzia_metadata.csv")

In [39]:
df_meta

,field,prefix,label
0,rischio_adulti,Indice regionale,Fattori di Rischio Potenziali Maltrattanti
1,servizi_adulti,Indice regionale,Servizi per Potenziali Maltrattanti
2,servizi_bambini,Indice regionale,Servizi per Bambini/e
3,rischio_bambini,Indice regionale,Sintomi Potenziale Maltrattamento dei Bambini/e
4,cura,Capacità di,Cura
5,vita_sana,Capacità di,Vivere una Vita Sana
6,vita_sicura,Capacità di,Vivere una Vita Sicura
7,conoscenza_sapere,Capacità di,Acquisire Conoscenza e Sapere
8,lavorare,Capacità di,Lavorare
9,accedere_risorse,Capacità di,Accedere alle Risorse e ai Servizi
10,rischio,Indice regionale,Fattori di rischio
11,servizi,Indice regionale,Servizi
12,totale,Indice regionale,Maltrattamento e Cura all'Infanzia in Italia

In [43]:
df.set_index(["territory", "year", "index"]).loc['Veneto']

                              capacity  score
year index
2019 rischio                       NaN  0.492
     servizi                       NaN  1.208
     totale                        NaN  0.799
     rischio_adulti   accedere_risorse  0.855
     servizi_adulti   accedere_risorse  1.470
...                                ...    ...
2024 rischio_bambini         vita_sana  0.210
     servizi_adulti          vita_sana  0.774
     servizi_bambini         vita_sana -0.333
     rischio_adulti        vita_sicura  0.293
     servizi_adulti        vita_sicura  0.176

[90 rows x 2 columns]

In [54]:
indice['rischi'].unstack()

year                              2019      2020      2021      2022      2024
territory
Abruzzo                      -0.432333 -0.395750 -0.415000 -0.331833 -0.347000
Basilicata                   -0.363500 -0.459750 -0.541333 -0.396750 -0.355833
Calabria                     -0.421750 -0.515417 -0.302917 -0.409083 -0.361417
Campania                     -0.988167 -0.961250 -0.948417 -0.952583 -0.913500
Emilia-Romagna                0.427083  0.490500  0.506417  0.428000  0.499750
Friuli-Venezia Giulia         0.613250  0.609000  0.599167  0.645833  0.745333
Lazio                         0.271583  0.222583  0.355833  0.370000  0.242167
Liguria                       0.174667  0.275667  0.278417  0.251917  0.153250
Lombardia                     0.337333  0.333000  0.331583  0.322667  0.406083
Marche                        0.471000  0.359417  0.343917  0.321667  0.343333
Molise                       -0.421167 -0.495417 -0.503250 -0.416750 -0.492250
Piemonte                      0.217250  0.280583  0.236917  0.141917  0.206750
Puglia                       -0.901500 -0.793333 -0.878000 -0.867917 -0.861917
Sardegna                     -0.579333 -0.528333 -0.474583 -0.547417 -0.476250
Sicilia                      -0.986083 -0.984500 -0.921000 -1.014500 -1.139417
Toscana                       0.448250  0.383333  0.399583  0.432917  0.441417
Trentino-Alto Adige/Südtirol  0.948500  0.936667  0.969333  0.834417  0.941500
Umbria                        0.088167  0.180750  0.206250  0.109083  0.178750
Valle d'Aosta/Vallée d'Aoste  0.536083  0.610167  0.393250  0.652083  0.372833
Veneto                        0.388833  0.400667  0.363417  0.507083  0.345750

In [8]:
df.set_index(["territory", "year"]).loc[('Veneto', 2024)]

/var/folders/cb/7slclp_j7lz2b62d1vg9y2yh0000gn/T/ipykernel_93354/923011740.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df.set_index(["territory", "year"]).loc[('Veneto', 2024)]

                         capacity            index  score
territory year
Veneto    2024   accedere_risorse   rischio_adulti  0.689
          2024   accedere_risorse   servizi_adulti  0.199
          2024  conoscenza_sapere   rischio_adulti  0.451
          2024  conoscenza_sapere   servizi_adulti -1.189
          2024               cura   rischio_adulti  0.426
          2024               cura   servizi_adulti  0.364
          2024               cura  servizi_bambini -0.002
          2024           lavorare   rischio_adulti  0.905
          2024           lavorare   servizi_adulti  3.949
          2024          vita_sana   rischio_adulti  0.125
          2024          vita_sana  rischio_bambini  0.210
          2024          vita_sana   servizi_adulti  0.774
          2024          vita_sana  servizi_bambini -0.333
          2024        vita_sicura   rischio_adulti  0.293
          2024        vita_sicura   servizi_adulti  0.176

In [10]:
mean = (0.689 + 0.451 + 0.426 + 0.905 + 0.125 + 0.210 + 0.293) / 7
print(mean)

0.4427142857142857